- name: check kubectl available
  stat:
    path: /usr/local/bin/kubectl
  register: kubectl_location
- name: install kubectl
  shell: "wget https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl -O /usr/local/bin/kubectl"
  when: kubectl_location.stat.exists == False
- name: set permissions on kubectl
  file:
    path: /usr/local/bin/kubectl
    mode: "0775"
- name: check kops available
  stat: 
    path: /usr/local/bin/kops
  register: kops_location
- name: install kops
  shell: "wget https://github.com/kubernetes/kops/releases/download/1.8.1/kops-linux-amd64 -O /usr/local/bin/kops"
  when: kops_location.stat.exists == False
- name: set permissions on kops
  file:
    path: /usr/local/bin/kops
    mode: "0775"
